CREATE TABLE KOS_FILE_IMAGE (    
     FNUM   VARCHAR2(20) PRIMARY KEY 
    ,FNAME  VARCHAR2(200)
    ,FPATH  VARCHAR2(300)
    ,INSERTDATE DATE
    ,UPDATEDATE DATE    
);

DELETE FROM KOS_FILE_IMAGE;
COMMIT;
SELECT * FROM KOS_FILE_IMAGE WHERE FNUM=2;

/*
시퀀스 
CREATE SEQUENCE [시퀀스명]
INCREMENT BY [N] -- 증가 숫자
START WITH [N] -- 시작 숫자
MINVALUE [N] -- 최소값
MAXVALUE [N] -- 최대값                               
CYCLE OR NOCYCLE -- CYCLE 설정시 최대값에 도달하면 최소값부터 다시 시작 NOCYCLE 설정시 최대값 생성 시 시퀀스 생성중지
CACHE OR NOCACHE -- CACHE 설정시 메모리에 시퀀스 값을 미리 할당하고 NOCACHE 설정시 시퀀스값을 메로리에 할당하지 않음
*/

CREATE SEQUENCE KOS_FILE_IMAGE_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999;

-- 순환하지 않음 
-- 메모리에 시퀀스값 미리 할당;

INSERT INTO KOS_FILE_IMAGE (FNUM, FNAME, FPATH, INSERTDATE, UPDATEDATE) 
VALUES (KOS_FILE_IMAGE_SEQ.NEXTVAL, '11', '11', SYSDATE, SYSDATE);

--해당 시퀀스 값 조회
SELECT KOS_FILE_IMAGE_SEQ.CURRVAL FROM DUAL; 
--전체 시퀀스 조회
SELECT * FROM USER_SEQUENCES;  

INSERT INTO KOS_FILE_IMAGE (FNUM, FNAME, FPATH, INSERTDATE, UPDATEDATE) VALUES ('11', '11', '11', SYSDATE, SYSDATE);

ROLLBACK;
COMMIT;
UPDATE KOS_FILE_IMAGE SET FNAME = 'test';