CREATE TABLE KOSMO_PRODUCT(
        MNUM  VARCHAR2(20) PRIMARY KEY
        ,MID  VARCHAR2(20)
        ,MCNT  VARCHAR2(20)
        ,MNAME  VARCHAR2(300)
        ,MPRICE  VARCHAR2(20)
        ,MDES  VARCHAR2(300)
        ,MCOM  VARCHAR2(300)
        ,MIMG  VARCHAR2(300)
        ,MINSERTDATE  DATE   NOT NULL
        ,MUPDATEDATE  DATE  NOT NULL
        ,MDELETEYN  VARCHAR(1) NOT NULL
);

SELECT*FROM KOSMO_PRODUCT;


-----
-- EMP 테이블에서 부서별로 부서 번호과 평균 급여
SELECT DEPTNO, AVG(SAL) AS SAL_AVG FROM EMP GROUP BY DEPTNO;

--  EMP 테이블에서 직책별로 직책과 평균 급여
SELECT JOB, AVG(SAL) AS SAL_AVG FROM EMP GROUP BY JOB;


SELECT*FROM EMP;


